# Generated by Django 4.1.7 on 2023-03-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('FedId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('superID', models.IntegerField(blank=True, default=0, null=True)),
                ('FederationName', models.TextField(max_length=100)),
                ('OfficialLetterhead', models.FileField(blank=True, null=True, upload_to='TheFiles/files')),
                ('Constitution', models.FileField(blank=True, null=True, upload_to='TheFiles/files')),
                ('last_AGM_Minutes', models.FileField(blank=True, null=True, upload_to='TheFiles/files')),
                ('Annual_Financial_Statement', models.FileField(blank=True, null=True, upload_to='TheFiles/files')),
                ('SARS_Tax_Clearance', models.CharField(default='Yes', max_length=3)),
                ('Tax_Clearance_Copy', models.FileField(blank=True, null=True, upload_to='TheFiles/files')),
                ('Child_Protection_Policies', models.CharField(default='Yes', max_length=3)),
                ('Child_Protection_Copy', models.FileField(blank=True, null=True, upload_to='TheFiles/files')),
            ],
        ),
    ]
